Cleaning up ProductPage mess
fromITzerotoIThero/IBOS pull request #18
Opened 2023-04-06 20:25 UTC by fromITzerotoIThero

2023-04-06 20:34 UTC, piotrwicijowski requested changes
Waiting for your changes

2023-04-06 20:34 UTC, piotrwicijowski commented on src/pages/ProductPage/ProductPage.jsx
> +    const currentPrice = null;
Are those values used?

2023-04-06 20:34 UTC, piotrwicijowski commented on src/pages/ProductPage/ProductPage.jsx
> +                        <img src={product.thumbnail_urls} alt={product.name} />
`thumbnail_urls` is an array, at least for now get the first element from it (assume that it always will have at least one)

2023-04-06 20:34 UTC, piotrwicijowski commented on src/pages/ProductPage/ProductPage.jsx
>          <div>
Do we need the wrapping div?

2023-04-06 20:34 UTC, piotrwicijowski commented on src/pages/ProductPage/ProductPage.module.css
> +    min-width: 9.5em;
Do we need the min width? Shouldn't the size be determined by the content and the padding?

2023-04-06 20:34 UTC, piotrwicijowski commented on src/pages/ProductPage/ProductPage.module.css
> +    padding: 2rem 2rem 2rem 1rem;
Why not just `padding: 2rem` all the way?

2023-04-06 20:36 UTC, fromITzerotoIThero commented on src/pages/ProductPage/ProductPage.jsx
> +    const currentPrice = null;
Waiting for them to be added to the database.

2023-04-06 20:39 UTC, fromITzerotoIThero commented on src/pages/ProductPage/ProductPage.jsx
>          <div>
Yeah, we do need it!

2023-04-06 20:49 UTC, piotrwicijowski approved these changes

2023-04-06 20:50 UTC, merged

2023-04-06 22:20 UTC, fromITzerotoIThero commented
So the PR shows as a yet another task! How cool is that! 
Seems to be a good place to ask more questions about the VS-Git-GitHub workflow.

1. I've noticed a button `Publish Branch` in Source Control - do I need to do it before I commit to the branch or does that happen automatically? 
2. Say I work on a feature but I know it's far from a PR (because I do a PR when I think that the code complete and it only waits for your review and my post-review changes, right?) what is the best way to ask for a quick code review? Make a commit on the feature branch and ask you to have a look?

2023-04-07 07:08 UTC, piotrwicijowski commented
1. If you create a branch locally and try to push to that, then VS Code will ask you to publish it, so it does the `Publish Branch` for you behind the scenes.
2. You can create a "draft PR" for that - it is signalling "I'm not done", but at the same time it gives the reviewer a nice place to have a conversation about the changes that you are working on. In order to do so, start creating a pull request, and on the "create PR" button there is a dropdown on the right which allows you to create a draft PR instead. I highly recommend it.

2023-04-07 09:32 UTC, fromITzerotoIThero commented
Oh that sounds just great, thx!!! 
I have another question - I wanted to check out for another branch so I clicked the branch icon in the bottom left corner, had the Command Palette open up and what I saw where branches with 'the tree' icon (local, I assume) and branches with 'the cloud' called `origin` (remote) - when do I use the latter?

![IMG-9436](https://user-images.githubusercontent.com/109156809/230583651-fdd79f37-a118-4a6e-be4c-92199bb6fcaf.jpg)

2023-04-07 11:37 UTC, piotrwicijowski commented
99% of the time the local branch state will match the remote branch state, so choosing one over the other should make no difference, so just go with the "tree icon", which indicates local branch. Also - always make sure to do a Pull, this would make sure that the latest changes from github are reflected in your machine, and that your local branch is matching with remote branch.
The only time when it makes sense to check out the remote branch, is when looking at someone else's code - then the branch exists only on remote, but in order to run it on your machine you need to have a local corresponding branch. I hope it makes sense.